### ISSUE TITLE
/src/mmp2_processing.py:57: ParserWarning: Length of header or names does not match length of data

### ISSUE THREAD

**Issue by marieleoz** [microbiome-gastro-UMG/MeTaPONT#3]
Dear Tim,

Thanks a lot for solving my previous issue! I successfully ran a first test to the end :) 
Please could you help me with 3 new issues/questions that emerged?

1) Is it expected that no abundance is calculated by Centrifuge? Here's what the log says:
report file centrifuge_report.tsv
Number of iterations in EM algorithm: 0
Probability diff. (P - P_prev) in the last iteration: 0
Calculating abundance: 00:00:00

(see TEST4.log attached)
[TEST4.log](https://github.com/microbiome-gastro-UMG/MeTaPONT/files/8262563/TEST4.log)

Indeed the "abundance" column in centrifuge_report.tsv only has 0.00 values. 

2) The issue arises after minimap has processed all the TaxIDs, I get a series of this:
/src/mmp2_processing.py:57: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  tmp_df = pd.read_csv(output_dir + '/minimap2output/' + file, index_col=False, sep='\t',

Not sure whether this is critical and how to fix it if needed?

3) Is it expected that the only output files (besides centrifuge_report.tsv, that I actually found in the database folder) are centrifuge_out.tsv and readIDTaxID.txt files?

Thanks a lot!

Best,
Marie

**Comment by tim488** [comment]
Dear Marie, 
can you please provide your Input file? I would like to reproduce your problems.
Best,
Tim

**Comment by marieleoz** [comment]
Thanks to you both!

Tim, here's a link to the single fastq file I used for TEST4: https://we.tl/t-mGZzKo4k4k

In the meantime I went on with the full series of fastq files I got for this sample, and got some more errors at the end + the readIDTaxID was not produced at all:

Traceback (most recent call last):
  File "/src/mmp2_processing.py", line 57, in <module>
    tmp_df = pd.read_csv(output_dir + '/minimap2output/' + file, index_col=False, sep='\t',
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1250, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 23 fields in line 9195, saw 24

python /src/mmp2_processing.py /files/ 1000:50 0 true
cp: cannot stat '/files//readIDTaxID*': No such file or directory

Please let me know if I should create a separate issue and/or send you more data for this one.

Apologies for the trouble :)

Best,
Marie

**Comment by marieleoz** [comment]
Dear Tim,

Any luck with your investigations? I ran the analysis again on the single fastq file but in verbose mode. See TEST4verb.log attached (if needed I can also provide with some more files that were produced during the run)
[TEST4verb.log](https://github.com/microbiome-gastro-UMG/MeTaPONT/files/8408419/TEST4verb.log)

I don't know if you noticed earlier but it looks like minimap fails processing TaxID 9 (the first one to be processed). It gets stuck there a while, then moves on to TaxID 545 and indicates:
/src/metapont: line 163:    69 Killed                  minimap2 -2 -c --secondary=no -t "$threads" -x map-ont "$(dirname $reference_seqs)/fastaTaxID/$taxID.gz" "$tmp_directory/minimap2output/temp.fq" > "$tmp_directory/minimap2output/$taxID.paf"

Couldn't this be why we then get errors such as "Length of header or names does not match length of data" or "Expected 23 fields in line 9195, saw 24"? 

Looking forward to hearing from you.

Best,
Marie

**Comment by marieleoz** [comment]
Ok great! Thank you Tim. Looking froward to hearing back from you.
Cheers,
Marie
 

Le Lundi, Avril 25, 2022 15:33 CEST, tim488 ***@***.***> a écrit:

**Comment by tim488** [comment]
Hey Marie,
the 2. Issue from your first post on top of this page is not an issue.
`/src/mmp2_processing.py:57: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.` can be ignored.

**Why does this Warning show?**
Minimap2 returns a table with varying amount of columns (i.e. one row has 15 columns, next row has 20 columns) this is because it returns a PAF formatted File and on each row appends a SAM formatted line.
If you still have the verbose output you should be able to have a look inside an <taxID>.paf file and see the tokenized SAM format for yourself.
Now, the pandas library, that I used for reading in this table gives errors if there are more columns in a row than it expects. To fix this, I told the thing it should expect more columns. This leads to the warning, because columns after the first 23 are cut of.
All we do with the appended SAM columns is to look for the `AS` Tag, which is the Alignment Score, which is in the first 23 columns, the rest is not interesting for us, as it just gives the coordinates of the Minimap2 hits (as far as I remember).
There is a List about the different columns of the minimap2 output here https://lh3.github.io/minimap2/minimap2.html (scroll down)

As for the one you reported on March 17th `pandas.errors.ParserError: Error tokenizing data. C error: Expected 23 fields in line 9195, saw 24` this is weird and exactly what I tried to prevent (I think). Can you by chance give me line 9195?

I have not seen the 69 killed Error before. I found [here](https://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux) that it could be an error message telling 'service unavailable'. Can you try if this happens if you submit a subset of your data? Maybe the dataset was to large.

I am sorry that you had to wait some time, but I do this in my free time/ as a hobby so please be a bit patient :-)

Cheers, 
Tim

**Comment by Christoph-Ammer** [comment]
Dear Marie,

sorry for the delay, but everything supposed to be fine right now. We tested the updated version from the scratch and no error or issue occurs anymore. Hope the pipeline is working for you as well. If you have further issues please do not hesitate dropping a new issue or comment.

Best

Christoph

**Comment by marieleoz** [comment]
Dear Christoph,

It does work for me as well :)
Thanks a lot!

Best,
Marie

 
Le Dimanche, Mai 15, 2022 09:34 CEST, Christoph-Ammer ***@***.***> a écrit:
